/* frecuencias */

.set DOBs,3623
.set REBs,3225
.set FAB, 2873
.set FABs, 2702
.set SOLBs,2415
.set LABs,2146

.set DO, 1915
.set DOs, 1805
.set RE, 1706
.set REs,1607 
.set MI, 1515
.set FA, 1433     @ Retardo para nota Fa = F
.set FAs, 1351
.set SOL, 1275
.set SOLs, 1204 @ Retardo para nota SOLs = Gs
.set LA, 1136     @ Retardo para nota La = A
.set LAs, 1072
.set SI, 1012

.set DOH, 956    @ Retardo para nota DoH = cH
.set DOHs, 902
.set REH, 851
.set REHs, 803

.set MIH, 758     @ Retardo para nota MIH = eH
.set FAH, 716     @ Retardo para nota FAH = FH
.set FAHs, 676
.set SOLH, 638
.set SOLHs, 602
.set LAH, 568



.set SILEN, 555  @silencio


/* duraciones */

.set P,2
.set NG,  500000
.set CORP,  375000
.set COR,    250000
.set FUS,   125000
.set BL, 1000000
